### ISSUE TITLE
Question on bc_ee_add_product_surcharge.php

### ISSUE THREAD

**Issue by shewards** [eventespresso/ee-code-snippet-library#9]
Silly questions, I'm sure...

Where does the code for the array go?

Do you have a suggestion as to where to put the other code?  Says anywhere, then gives LOTS of conditions, AND says to comment it out...?

-Steve
Not Afraid to Ask a Dumb Question

**Comment by nsidev** [comment]
Good question. I just started using this today and it dawned on me: no reports. I need to accumulate a listing of shirt sales, by name, size. Please advise ASAP! Time is money, my friend!

**Comment by tn3rb** [comment]
If you are unsure or not an experienced developer, then it's probably best to just leave everything in that one file and just include that file from your theme's functions.php file:

```php
require_once '/full/server/path/to/bc_ee_add_product_surcharge.php';
```

That will of course mean that you will have to hardcode all of the details into the products array.

If you are more experienced and need to generate the list of products dynamically, then I can't really comment on where to do that because I don't know the setup of your system or what you are even trying to integrate with, ie: another cart? custom wordpress admin? etc, but at that point, you would know where some additional code would fit best in your system. Ideally you would take the code that I wrote in that snippet and either add it to a plugin that you already have for adding functionality to your site, or you would create a new plugin and put everything into that, including your logic for dynamically generating product data. But that goes way **way** **WAY** beyond the scope of support that we offer here.

Please don't take the above to me that I'm not happy to help you with any questions regarding any other code in that snippet, or to help you with any issues you may encounter after integrating that code into your site. I just do not have the time to teach someone about more advanced development practices and have no choice but to suggest you explore the vast number of tutorials out there on the topic.

**Comment by shewards** [comment]
Thanks for the thoughtful response.  I should have expected it, but just wanted to be sure.  I've opted to add the code to the plugin I made initially to add flexibility to the EE Upcoming Events widget.  I've also hard-coded the quantity to 1, as I'm pretty sure my needs will be covered by "do you want it or not?" kind of questions, and that looks better on the registration page anyway.
One suggestion I'd have is to add to the example a XXXL shirt, and quote Homer Simpson in the description - "I don't wanna look like a freak!  Gimme the moomoo!"
